<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INLEN8520039525" failures="2" tests="10" name="org.example.tests.sampleTestClass1" time="0.079" errors="0" timestamp="2025-01-02T22:36:30 IST" skipped="8">
  <testcase classname="org.example.tests.sampleTestClass1" name="testCase2" time="0.036">
    <skipped/>
  </testcase> <!-- testCase2 -->
  <system-out/>
  <testcase classname="org.example.tests.sampleTestClass1" name="testCase2" time="0.001">
    <skipped/>
  </testcase> <!-- testCase2 -->
  <system-out/>
  <testcase classname="org.example.tests.sampleTestClass1" name="testCase2" time="0.000">
    <skipped/>
  </testcase> <!-- testCase2 -->
  <system-out/>
  <testcase classname="org.example.tests.sampleTestClass1" name="testCase2" time="0.001">
    <skipped/>
  </testcase> <!-- testCase2 -->
  <system-out/>
  <testcase classname="org.example.tests.sampleTestClass1" name="testCase2" time="0.001">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:976)
at org.testng.Assert.assertEquals(Assert.java:1010)
at org.example.tests.sampleTestClass1.testCase2(sampleTestClass1.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <system-out/>
  <testcase classname="org.example.tests.sampleTestClass1" name="testCase1" time="0.000">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <system-out/>
  <testcase classname="org.example.tests.sampleTestClass1" name="testCase1" time="0.003">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:976)
at org.testng.Assert.assertEquals(Assert.java:1010)
at org.example.tests.sampleTestClass1.testCase1(sampleTestClass1.java:10)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <system-out/>
  <testcase classname="org.example.tests.sampleTestClass1" name="testCase1" time="0.036">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <system-out/>
  <testcase classname="org.example.tests.sampleTestClass1" name="testCase1" time="0.001">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <system-out/>
  <testcase classname="org.example.tests.sampleTestClass1" name="testCase1" time="0.000">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <system-out/>
</testsuite> <!-- org.example.tests.sampleTestClass1 -->
